services:
  backend:
    image: backend
    container_name: backend
    build: 
      context: .
      dockerfile: dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      # - "./app:/app/app"
      - "./app:/backend_app/app"

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
    depends_on:
      - postgres   

volumes:
  db_data:
  pgadmin_data: 