FROM python:3-slim

# ตั้ง working directory ภายใน container
WORKDIR /backend_app

# คัดลอกไฟล์ requirements.txt เข้า /backend_app
COPY requirements.txt .

RUN python -m pip install --no-cache-dir -r requirements.txt

# คัดลอกไฟล์โค้ดทั้งหมดเข้า /backend_app
COPY . /backend_app


EXPOSE 8000
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]