services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi_api
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app          # bind โค้ดตรง ๆ
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: fastapi_db
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: fastapi_pgadmin
    ports:
      - "5050:80"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db_data:
